[window]
dynamic_padding = true
padding.x = 11
padding.y = 11
dynamic_title = true

[terminal.shell]
program = "/usr/bin/fish"

[general]
live_config_reload = true
import = [
    # "~/.config/alacritty/themes/themes/miasma.toml"
    "colors.toml"
]

[terminal]

